# code:language=ansible
---
- name: Remove dependencies that are no longer needed for RedHat family
  when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky" or ansible_os_family == "AlmaLinux"
  ansible.builtin.dnf:
    autoremove: true

- name: Clean dnf cache
  when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky" or ansible_os_family == "AlmaLinux"
  ansible.builtin.command:
    cmd: >
      dnf clean all
  tags:
    - molecule-idempotence-notest
    - skip_ansible_lint

- name: Remove dependencies that are no longer needed for Debian family
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Clean apt cache
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    clean: true
    autoclean: true
  tags:
    - molecule-idempotence-notest
