# code:language=ansible
---
- name: Install OS updates (include dist-upgrade)
  when: os_update_dist_upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: "full"

- name: Install OS updates (no dist-upgrade)
  when: not os_update_dist_upgrade
  ansible.builtin.apt:
    update_cache: true
    name:
      - "*"
    state: latest
  tags:
    - skip_ansible_lint

- name: Check if reboot is required
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Update reboot fact
  when:
    - (reboot_required.stat.exists and os_update_reboot != "NEVER") or os_update_reboot == "ALWAYS"
  ansible.builtin.set_fact:
    reboot_machine: true
