# code:language=ansible
---
- name: Set reboot fact
  ansible.builtin.set_fact:
    reboot_machine: false

- name: Install OS updates for RedHat family
  when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky" or ansible_os_family == "AlmaLinux"
  ansible.builtin.include_tasks:
    file: RedHat.yml

- name: Install OS updates for Debian family
  when: ansible_os_family == "Debian"
  ansible.builtin.include_tasks:
    file: Debian.yml

- name: Install OS updates for Alpine
  when: ansible_facts['distribution'] == 'Alpine'
  ansible.builtin.include_tasks:
    file: Alpine.yml

- name: Restart system
  when: reboot_machine
  ansible.builtin.reboot:
    reboot_timeout: "{{ os_update_reboot_timeout }}"
    pre_reboot_delay: "{{ os_update_reboot_delay }}"
  tags:
    - molecule-notest

- name: Cleanup package caches
  when: os_update_cleanup
  ansible.builtin.include_tasks:
    file: clean.yml
