name: lint

on:
  push:
    branches:
      - "**"
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: lint
        uses: ansible/ansible-lint@v24.6.0
