name: publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: publish role
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: "{{ secrets.ANSIBLE_GALAXY_API_KEY }}"
